2025-03-08 12:32:14,919 INFO    MainThread:585303 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-08 12:32:14,921 INFO    MainThread:585303 [wandb_setup.py:_flush():67] Configure stats pid to 585303
2025-03-08 12:32:14,921 INFO    MainThread:585303 [wandb_setup.py:_flush():67] Loading settings from /homes/nmorelli/.config/wandb/settings
2025-03-08 12:32:14,922 INFO    MainThread:585303 [wandb_setup.py:_flush():67] Loading settings from /homes/nmorelli/aibio_nico/source/wandb/settings
2025-03-08 12:32:14,922 INFO    MainThread:585303 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-08 12:32:14,922 INFO    MainThread:585303 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123214-0yhpt8f1/logs/debug.log
2025-03-08 12:32:14,923 INFO    MainThread:585303 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123214-0yhpt8f1/logs/debug-internal.log
2025-03-08 12:32:14,924 INFO    MainThread:585303 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fe1ac0523a0>
2025-03-08 12:32:14,925 INFO    MainThread:585303 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:32:14,926 INFO    MainThread:585303 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'net': 'simclr', 'backbone_name': 'vit_tiny', 'checkpoint_dir': '/homes/nmorelli/aibio_nico/checkpoint', 'dataset_dir': '/work/ai4bio2024/rxrx1', 'load_checkpoint': None, 'load_backbone': None, 'metadata_path': '/work/ai4bio2024/rxrx1/rxrx1_v1.0/metadata.csv', 'epochs': 20, 'batch_size': 16, 'loss': 'simclrloss', 'opt': 'adam', 'lr': 0.005, 'evaluation_freq': 4, 'model_save_freq': 10, 'sched_pow': 3, 'num_classes': 2, 'device': 'gpu', 'multiple_gpus': True, 'train_workers': 16, 'evaluation_workers': 16, 'project_name': 'aibio_prj', 'run_name': 'simclr_backbone_vit_large', '_wandb': {}}
2025-03-08 12:32:14,926 INFO    MainThread:585303 [wandb_init.py:init():784] starting backend
2025-03-08 12:32:14,926 INFO    MainThread:585303 [wandb_init.py:init():788] sending inform_init request
2025-03-08 12:32:14,941 INFO    MainThread:585303 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-08 12:32:14,942 INFO    MainThread:585303 [wandb_init.py:init():798] backend started and connected
2025-03-08 12:32:14,994 INFO    MainThread:585303 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-08 12:32:14,996 INFO    MainThread:585303 [wandb_init.py:init():891] updated telemetry
2025-03-08 12:32:14,998 INFO    MainThread:585303 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-08 12:32:15,399 INFO    MainThread:585303 [wandb_init.py:init():990] starting run threads in backend
2025-03-08 12:32:16,485 INFO    MainThread:585303 [wandb_run.py:_console_start():2375] atexit reg
2025-03-08 12:32:16,486 INFO    MainThread:585303 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-08 12:32:16,487 INFO    MainThread:585303 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-08 12:32:16,499 INFO    MainThread:585303 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-08 12:32:16,508 INFO    MainThread:585303 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-08 12:32:16,508 INFO    MainThread:585303 [wandb_run.py:_config_callback():1261] config_cb None None {'seed': 333}
2025-03-08 12:33:02,298 INFO    MainThread:585888 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,299 INFO    MainThread:585888 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,303 INFO    MainThread:585935 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,303 INFO    MainThread:585935 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,305 INFO    MainThread:585909 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,306 INFO    MainThread:585909 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,316 INFO    MainThread:585930 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,316 INFO    MainThread:585930 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,320 INFO    MainThread:585942 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,320 INFO    MainThread:585942 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,323 INFO    MainThread:585902 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,323 INFO    MainThread:585902 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,323 INFO    MainThread:585905 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,324 INFO    MainThread:585905 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,324 INFO    MainThread:585917 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,324 INFO    MainThread:585917 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,327 INFO    MainThread:585938 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,328 INFO    MainThread:585938 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,330 INFO    MainThread:585923 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,330 INFO    MainThread:585923 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,362 INFO    MainThread:585920 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,362 INFO    MainThread:585927 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,362 INFO    MainThread:585899 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,362 INFO    MainThread:585893 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,362 INFO    MainThread:585920 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,363 INFO    MainThread:585896 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,362 INFO    MainThread:585893 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,363 INFO    MainThread:585912 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,362 INFO    MainThread:585899 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,362 INFO    MainThread:585927 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,363 INFO    MainThread:585896 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,363 INFO    MainThread:585912 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,249 WARNING MsgRouterThr:585303 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-08 12:33:02,305 INFO    MainThread:585303 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:02,365 INFO    MsgRouterThr:585303 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-08 12:33:02,365 INFO    MainThread:585303 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:02,417 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:02,494 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:03,438 INFO    MainThread:585303 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:33:03,440 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:03,447 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:03,497 INFO    MainThread:585303 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:03,497 INFO    MainThread:585303 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:03,498 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:03,500 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:05,889 INFO    MainThread:585303 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:33:05,890 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:05,893 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:05,937 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:05,939 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:05,940 INFO    MainThread:585303 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:05,940 INFO    MainThread:585303 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:05,941 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:05,943 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:07,478 INFO    MainThread:585303 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:33:07,482 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:07,484 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:07,537 INFO    MainThread:585303 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:07,537 INFO    MainThread:585303 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:07,539 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:07,542 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:08,103 INFO    MainThread:585303 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:33:08,105 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:08,111 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:15,750 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:15,827 INFO    MainThread:585303 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123315-tfh7sxjq/logs/debug.log
2025-03-08 12:33:15,828 INFO    MainThread:585303 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123315-tfh7sxjq/logs/debug-internal.log
2025-03-08 12:33:15,833 INFO    MainThread:585303 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:33:15,834 INFO    MainThread:585303 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'net': 'simclr', 'backbone_name': 'vit_tiny', 'checkpoint_dir': '/homes/nmorelli/aibio_nico/checkpoint', 'dataset_dir': '/work/ai4bio2024/rxrx1', 'load_checkpoint': None, 'load_backbone': None, 'metadata_path': '/work/ai4bio2024/rxrx1/rxrx1_v1.0/metadata.csv', 'epochs': 20, 'batch_size': 16, 'loss': 'simclrloss', 'opt': 'adam', 'lr': 0.005, 'evaluation_freq': 4, 'model_save_freq': 10, 'sched_pow': 3, 'num_classes': 2, 'device': 'gpu', 'multiple_gpus': True, 'train_workers': 16, 'evaluation_workers': 16, 'project_name': 'aibio_prj', 'run_name': 'simclr_backbone_vit_large', '_wandb': {}}
2025-03-08 12:33:15,834 INFO    MainThread:585303 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-08 12:33:15,835 ERROR   MainThread:585303 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    tel.feature.init_return_run = True
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:15,946 INFO    MainThread:585303 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:15,946 INFO    MainThread:585303 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:15,947 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:15,951 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:15,987 INFO    MainThread:585303 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:33:15,988 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:15,989 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:16,013 INFO    MainThread:585303 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:16,013 INFO    MainThread:585303 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:16,014 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:16,015 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:18,037 INFO    MainThread:585303 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:33:18,040 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:18,044 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:18,089 INFO    MainThread:585303 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:18,089 INFO    MainThread:585303 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:18,090 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:18,092 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:18,606 INFO    MainThread:585303 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:33:18,607 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:18,613 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:18,748 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:18,825 INFO    MainThread:585303 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123318-et2wro64/logs/debug.log
2025-03-08 12:33:18,825 INFO    MainThread:585303 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123318-et2wro64/logs/debug-internal.log
2025-03-08 12:33:18,826 INFO    MainThread:585303 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:33:18,826 INFO    MainThread:585303 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'net': 'simclr', 'backbone_name': 'vit_tiny', 'checkpoint_dir': '/homes/nmorelli/aibio_nico/checkpoint', 'dataset_dir': '/work/ai4bio2024/rxrx1', 'load_checkpoint': None, 'load_backbone': None, 'metadata_path': '/work/ai4bio2024/rxrx1/rxrx1_v1.0/metadata.csv', 'epochs': 20, 'batch_size': 16, 'loss': 'simclrloss', 'opt': 'adam', 'lr': 0.005, 'evaluation_freq': 4, 'model_save_freq': 10, 'sched_pow': 3, 'num_classes': 2, 'device': 'gpu', 'multiple_gpus': True, 'train_workers': 16, 'evaluation_workers': 16, 'project_name': 'aibio_prj', 'run_name': 'simclr_backbone_vit_large', '_wandb': {}}
2025-03-08 12:33:18,827 INFO    MainThread:585303 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-08 12:33:18,827 ERROR   MainThread:585303 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    tel.feature.init_return_run = True
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:18,923 INFO    MainThread:585303 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:18,924 INFO    MainThread:585303 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:18,924 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:18,926 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:19,169 INFO    MainThread:585303 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:33:19,170 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:19,171 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:19,196 INFO    MainThread:585303 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:33:19,196 INFO    MainThread:585303 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:33:19,197 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:33:19,198 ERROR   MainThread:585303 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
