2025-03-08 12:34:39,651 INFO    MainThread:587059 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123439-zblwmw74/logs/debug.log
2025-03-08 12:34:39,652 INFO    MainThread:587059 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123439-zblwmw74/logs/debug-internal.log
2025-03-08 12:34:39,652 INFO    MainThread:587059 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:34:39,653 INFO    MainThread:587059 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'net': 'simclr', 'backbone_name': 'vit_tiny', 'checkpoint_dir': '/homes/nmorelli/aibio_nico/checkpoint', 'dataset_dir': '/work/ai4bio2024/rxrx1', 'load_checkpoint': None, 'load_backbone': None, 'metadata_path': '/work/ai4bio2024/rxrx1/rxrx1_v1.0/metadata.csv', 'epochs': 20, 'batch_size': 16, 'loss': 'simclrloss', 'opt': 'adam', 'lr': 0.005, 'evaluation_freq': 4, 'model_save_freq': 10, 'sched_pow': 3, 'num_classes': 2, 'device': 'gpu', 'multiple_gpus': True, 'train_workers': 16, 'evaluation_workers': 16, 'project_name': 'aibio_prj', 'run_name': 'simclr_backbone_vit_large', '_wandb': {}}
2025-03-08 12:34:39,653 INFO    MainThread:587059 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-08 12:34:39,654 ERROR   MainThread:587059 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    tel.feature.init_return_run = True
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:39,747 INFO    MainThread:587059 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:39,747 INFO    MainThread:587059 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:39,748 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:39,749 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
