2025-03-08 12:33:54,933 INFO    MainThread:587059 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-08 12:33:54,934 INFO    MainThread:587059 [wandb_setup.py:_flush():67] Configure stats pid to 587059
2025-03-08 12:33:54,935 INFO    MainThread:587059 [wandb_setup.py:_flush():67] Loading settings from /homes/nmorelli/.config/wandb/settings
2025-03-08 12:33:54,935 INFO    MainThread:587059 [wandb_setup.py:_flush():67] Loading settings from /homes/nmorelli/aibio_nico/source/wandb/settings
2025-03-08 12:33:54,935 INFO    MainThread:587059 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-08 12:33:54,936 INFO    MainThread:587059 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123354-7jcist6i/logs/debug.log
2025-03-08 12:33:54,937 INFO    MainThread:587059 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123354-7jcist6i/logs/debug-internal.log
2025-03-08 12:33:54,937 INFO    MainThread:587059 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fba2c0ed1f0>
2025-03-08 12:33:54,939 INFO    MainThread:587059 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:33:54,940 INFO    MainThread:587059 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'net': 'simclr', 'backbone_name': 'vit_tiny', 'checkpoint_dir': '/homes/nmorelli/aibio_nico/checkpoint', 'dataset_dir': '/work/ai4bio2024/rxrx1', 'load_checkpoint': None, 'load_backbone': None, 'metadata_path': '/work/ai4bio2024/rxrx1/rxrx1_v1.0/metadata.csv', 'epochs': 20, 'batch_size': 16, 'loss': 'simclrloss', 'opt': 'adam', 'lr': 0.005, 'evaluation_freq': 4, 'model_save_freq': 10, 'sched_pow': 3, 'num_classes': 2, 'device': 'gpu', 'multiple_gpus': True, 'train_workers': 16, 'evaluation_workers': 16, 'project_name': 'aibio_prj', 'run_name': 'simclr_backbone_vit_large', '_wandb': {}}
2025-03-08 12:33:54,940 INFO    MainThread:587059 [wandb_init.py:init():784] starting backend
2025-03-08 12:33:54,940 INFO    MainThread:587059 [wandb_init.py:init():788] sending inform_init request
2025-03-08 12:33:54,954 INFO    MainThread:587059 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-08 12:33:54,955 INFO    MainThread:587059 [wandb_init.py:init():798] backend started and connected
2025-03-08 12:33:55,007 INFO    MainThread:587059 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-08 12:33:55,009 INFO    MainThread:587059 [wandb_init.py:init():891] updated telemetry
2025-03-08 12:33:55,011 INFO    MainThread:587059 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-08 12:33:55,406 INFO    MainThread:587059 [wandb_init.py:init():990] starting run threads in backend
2025-03-08 12:33:56,521 INFO    MainThread:587059 [wandb_run.py:_console_start():2375] atexit reg
2025-03-08 12:33:56,526 INFO    MainThread:587059 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-08 12:33:56,527 INFO    MainThread:587059 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-08 12:33:56,529 INFO    MainThread:587059 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-08 12:33:56,536 INFO    MainThread:587059 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-08 12:33:56,536 INFO    MainThread:587059 [wandb_run.py:_config_callback():1261] config_cb None None {'seed': 333}
2025-03-08 12:34:30,690 WARNING MsgRouterThr:587059 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-08 12:34:30,695 INFO    MsgRouterThr:587059 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-08 12:34:30,742 INFO    MainThread:587847 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,742 INFO    MainThread:587847 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,744 INFO    MainThread:587844 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,744 INFO    MainThread:587844 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,744 INFO    MainThread:587857 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,745 INFO    MainThread:587857 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,745 INFO    MainThread:587872 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,746 INFO    MainThread:587059 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,746 INFO    MainThread:587872 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,746 INFO    MainThread:587883 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,746 INFO    MainThread:587883 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,746 INFO    MainThread:587059 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,746 INFO    MainThread:587860 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,746 INFO    MainThread:587860 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,748 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:30,763 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:30,772 INFO    MainThread:587886 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,772 INFO    MainThread:587868 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,772 INFO    MainThread:587868 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,772 INFO    MainThread:587886 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,773 INFO    MainThread:587863 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,773 INFO    MainThread:587863 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,775 INFO    MainThread:587875 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,775 INFO    MainThread:587875 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,784 INFO    MainThread:587878 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,784 INFO    MainThread:587839 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,784 INFO    MainThread:587878 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,784 INFO    MainThread:587839 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,784 INFO    MainThread:587890 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,784 INFO    MainThread:587853 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,784 INFO    MainThread:587893 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,784 INFO    MainThread:587850 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:30,785 INFO    MainThread:587890 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,785 INFO    MainThread:587853 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,785 INFO    MainThread:587850 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:30,785 INFO    MainThread:587893 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:33,808 INFO    MainThread:587059 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:34:33,809 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:33,811 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:33,855 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:33,856 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:33,857 INFO    MainThread:587059 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:33,857 INFO    MainThread:587059 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:33,858 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:33,860 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:35,367 INFO    MainThread:587059 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:34:35,369 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:35,372 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:35,419 INFO    MainThread:587059 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:35,419 INFO    MainThread:587059 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:35,419 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:35,421 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:35,981 INFO    MainThread:587059 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:34:35,983 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:35,987 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:39,562 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:39,651 INFO    MainThread:587059 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123439-zblwmw74/logs/debug.log
2025-03-08 12:34:39,652 INFO    MainThread:587059 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_123439-zblwmw74/logs/debug-internal.log
2025-03-08 12:34:39,652 INFO    MainThread:587059 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:34:39,653 INFO    MainThread:587059 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'net': 'simclr', 'backbone_name': 'vit_tiny', 'checkpoint_dir': '/homes/nmorelli/aibio_nico/checkpoint', 'dataset_dir': '/work/ai4bio2024/rxrx1', 'load_checkpoint': None, 'load_backbone': None, 'metadata_path': '/work/ai4bio2024/rxrx1/rxrx1_v1.0/metadata.csv', 'epochs': 20, 'batch_size': 16, 'loss': 'simclrloss', 'opt': 'adam', 'lr': 0.005, 'evaluation_freq': 4, 'model_save_freq': 10, 'sched_pow': 3, 'num_classes': 2, 'device': 'gpu', 'multiple_gpus': True, 'train_workers': 16, 'evaluation_workers': 16, 'project_name': 'aibio_prj', 'run_name': 'simclr_backbone_vit_large', '_wandb': {}}
2025-03-08 12:34:39,653 INFO    MainThread:587059 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-08 12:34:39,654 ERROR   MainThread:587059 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    tel.feature.init_return_run = True
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 60, in _publish_telemetry
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:39,747 INFO    MainThread:587059 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:34:39,747 INFO    MainThread:587059 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:34:39,748 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:34:39,749 ERROR   MainThread:587059 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
