2025-03-08 12:47:05,421 INFO    MainThread:603308 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-08 12:47:05,422 INFO    MainThread:603308 [wandb_setup.py:_flush():67] Configure stats pid to 603308
2025-03-08 12:47:05,423 INFO    MainThread:603308 [wandb_setup.py:_flush():67] Loading settings from /homes/nmorelli/.config/wandb/settings
2025-03-08 12:47:05,423 INFO    MainThread:603308 [wandb_setup.py:_flush():67] Loading settings from /homes/nmorelli/aibio_nico/source/wandb/settings
2025-03-08 12:47:05,424 INFO    MainThread:603308 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-08 12:47:05,424 INFO    MainThread:603308 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_124705-9z5329u2/logs/debug.log
2025-03-08 12:47:05,424 INFO    MainThread:603308 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /homes/nmorelli/aibio_nico/source/wandb/run-20250308_124705-9z5329u2/logs/debug-internal.log
2025-03-08 12:47:05,425 INFO    MainThread:603308 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f25a054a220>
2025-03-08 12:47:05,427 INFO    MainThread:603308 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:47:05,428 INFO    MainThread:603308 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'net': 'simclr', 'backbone_name': 'resnet50', 'checkpoint_dir': '/homes/nmorelli/aibio_nico/checkpoint', 'dataset_dir': '/work/ai4bio2024/rxrx1', 'load_checkpoint': None, 'load_backbone': None, 'metadata_path': '/work/ai4bio2024/rxrx1/rxrx1_v1.0/metadata.csv', 'epochs': 20, 'batch_size': 4, 'loss': 'simclrloss', 'opt': 'adam', 'lr': 0.005, 'evaluation_freq': 4, 'model_save_freq': 10, 'sched_pow': 3, 'num_classes': 2, 'device': 'gpu', 'multiple_gpus': False, 'train_workers': 2, 'evaluation_workers': 16, 'project_name': 'aibio_prj', 'run_name': 'simclr_backbone_vit_large', '_wandb': {}}
2025-03-08 12:47:05,428 INFO    MainThread:603308 [wandb_init.py:init():784] starting backend
2025-03-08 12:47:05,428 INFO    MainThread:603308 [wandb_init.py:init():788] sending inform_init request
2025-03-08 12:47:05,442 INFO    MainThread:603308 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-08 12:47:05,443 INFO    MainThread:603308 [wandb_init.py:init():798] backend started and connected
2025-03-08 12:47:05,499 INFO    MainThread:603308 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-08 12:47:05,501 INFO    MainThread:603308 [wandb_init.py:init():891] updated telemetry
2025-03-08 12:47:05,503 INFO    MainThread:603308 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-08 12:47:05,904 INFO    MainThread:603308 [wandb_init.py:init():990] starting run threads in backend
2025-03-08 12:47:06,940 INFO    MainThread:603308 [wandb_run.py:_console_start():2375] atexit reg
2025-03-08 12:47:06,942 INFO    MainThread:603308 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-08 12:47:06,942 INFO    MainThread:603308 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-08 12:47:06,944 INFO    MainThread:603308 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-08 12:47:06,950 INFO    MainThread:603308 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-08 12:47:06,951 INFO    MainThread:603308 [wandb_run.py:_config_callback():1261] config_cb None None {'seed': 333}
2025-03-08 12:47:54,882 WARNING MsgRouterThr:603308 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-08 12:47:54,888 INFO    MsgRouterThr:603308 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-08 12:47:54,926 INFO    MainThread:603308 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:47:54,926 INFO    MainThread:603308 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:47:54,962 INFO    MainThread:603842 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:47:54,962 INFO    MainThread:603842 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:47:54,968 INFO    MainThread:603847 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:47:54,968 INFO    MainThread:603847 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:48:31,255 INFO    MainThread:603308 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-08 12:48:31,256 ERROR   MainThread:603308 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:48:31,265 ERROR   MainThread:603308 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:48:31,305 INFO    MainThread:603308 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-08 12:48:31,305 INFO    MainThread:603308 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-08 12:48:31,306 ERROR   MainThread:603308 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-08 12:48:31,308 ERROR   MainThread:603308 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/events.py", line 89, in trigger
    func(*args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/homes/nmorelli/.local/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
